/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as AdminAssignmentsIndexRouteImport } from './routes/admin/assignments/index'
import { Route as AdminAssignmentsIdRouteImport } from './routes/admin/assignments/$id'
import { Route as AdminAssignmentsNewRouteImport } from './routes/admin/assignments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentsIndexRoute = AdminAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsIdRoute = AdminAssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsNewRoute = AdminAssignmentsNewRouteImport.update({
  id: '/assignments/new',
  path: '/assignments/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/admin/assignments/$id': typeof AdminAssignmentsIdRoute
  '/admin/assignments/new': typeof AdminAssignmentsNewRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/admin/assignments/$id': typeof AdminAssignmentsIdRoute
  '/admin/assignments/new': typeof AdminAssignmentsNewRoute
  '/admin/assignments': typeof AdminAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/admin/assignments/$id': typeof AdminAssignmentsIdRoute
  '/admin/assignments/new': typeof AdminAssignmentsNewRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login/'
    | '/submissions/'
    | '/admin/assignments/$id'
    | '/admin/assignments/new'
    | '/admin/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/submissions'
    | '/admin/assignments/$id'
    | '/admin/assignments/new'
    | '/admin/assignments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login/'
    | '/submissions/'
    | '/admin/assignments/$id'
    | '/admin/assignments/new'
    | '/admin/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignments/': {
      id: '/admin/assignments/'
      path: '/assignments'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AdminAssignmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments/$id': {
      id: '/admin/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/admin/assignments/$id'
      preLoaderRoute: typeof AdminAssignmentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments/new': {
      id: '/admin/assignments/new'
      path: '/assignments/new'
      fullPath: '/admin/assignments/new'
      preLoaderRoute: typeof AdminAssignmentsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAssignmentsIdRoute: typeof AdminAssignmentsIdRoute
  AdminAssignmentsNewRoute: typeof AdminAssignmentsNewRoute
  AdminAssignmentsIndexRoute: typeof AdminAssignmentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAssignmentsIdRoute: AdminAssignmentsIdRoute,
  AdminAssignmentsNewRoute: AdminAssignmentsNewRoute,
  AdminAssignmentsIndexRoute: AdminAssignmentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
